###
GET http://localhost:8080/

###
POST http://localhost:8080/json2
Content-Type: application/json

{
	"bool": true,
	"int": 2,
	"string": "s",
	"slice": [12],
	"map":  {
      "3": "1"
    },
    "hidden": "true"
}
